### ISSUE TITLE
Copying LDFx

### ISSUE THREAD

**Issue by ItsToxicGG** [Faizx511x/PowrCore#1]
Took ReadMe.MD From LDFx (made by me), please Give some credit,_,

**Comment by ItsToxicGG** [comment]
and all the features are tooked by my plugin also (not all but mostly all)

**Comment by Faizx511x** [comment]
Sorry

**Comment by ItsToxicGG** [comment]
like:
```md
# Credits
- ItsToxicGG (ReadMe.md)
```
